export const colorTable = [
  { hex: '#000000', en: 'Black', complimentary: 'Black' },
  { hex: '#000080', en: 'Navy blue', complimentary: 'Light Orange' },
  { hex: '#00008b', en: 'Dark blue', complimentary: 'Light Orange' },
  { hex: '#0000ff', en: 'Blue', complimentary: 'Orange' },
  { hex: '#006400', en: 'Dark green', complimentary: 'Red' },
  { hex: '#008000', en: 'Green', complimentary: 'Red' },
  { hex: '#008080', en: 'Teal', complimentary: 'Red' },
  { hex: '#00ff00', en: 'Lime', complimentary: 'Purple' },
  { hex: '#00ffff', en: 'Cyan', complimentary: 'Red' },
  { hex: '#191970', en: 'Midnight blue', complimentary: 'Yellow' },
  { hex: '#2E8B57', en: 'Sea green', complimentary: 'Red' },
  { hex: '#40e0d0', en: 'Turquoise', complimentary: 'Light Red' },
  { hex: '#4b0082', en: 'Indigo', complimentary: 'Red' },
  { hex: '#7fffd4', en: 'Aquamarine', complimentary: 'Orange' },
  { hex: '#800000', en: 'Maroon', complimentary: 'Light Blue' },
  { hex: '#800080', en: 'Purple', complimentary: 'Light Green' },
  { hex: '#808000', en: 'Olive', complimentary: 'Dark Purple' },
  { hex: '#808080', en: 'Gray', complimentary: 'Gray' },
  { hex: '#87ceeb', en: 'Sky blue', complimentary: 'Orange' },
  { hex: '#8b0000', en: 'Dark red', complimentary: 'Light Blue' },
  { hex: '#90ee90', en: 'Light green', complimentary: 'Purple' },
  { hex: '#a52a2a', en: 'Brown', complimentary: 'Light Blue' },
  { hex: '#a9a9a9', en: 'Dark gray', complimentary: 'Dark Gray' },
  { hex: '#add8e6', en: 'Light blue', complimentary: 'Red' },
  { hex: '#c0c0c0', en: 'Silver', complimentary: 'Silver' },
  { hex: '#d2b48c', en: 'Tan', complimentary: 'Dark Blue' },
  { hex: '#d3d3d3', en: 'Light gray', complimentary: 'Light Gray' },
  { hex: '#dc143c', en: 'Crimson', complimentary: 'Blue' },
  { hex: '#dda0dd', en: 'Plum', complimentary: 'Green' },
  { hex: '#e6e6fa', en: 'Lavender', complimentary: 'Green' },
  { hex: '#f0e68c', en: 'Khaki', complimentary: 'Dark Blue' },
  { hex: '#fa8072', en: 'Salmon', complimentary: 'Dark Blue' },
  { hex: '#ff0000', en: 'Red', complimentary: 'Green' },
  { hex: '#ff00ff', en: 'Fuchsia', complimentary: 'Green' },
  { hex: '#ff7f50', en: 'Coral', complimentary: 'Light Blue' },
  { hex: '#ffa500', en: 'Orange', complimentary: 'Blue' },
  { hex: '#ffc0cb', en: 'Pink', complimentary: 'Green' },
  { hex: '#ffd700', en: 'Gold', complimentary: 'Dark Blue' },
  { hex: '#fffafa', en: 'Snow', complimentary: 'White' },
  { hex: '#ffff00', en: 'Yellow', complimentary: 'Blue' },
  { hex: '#ffffff', en: 'White', complimentary: 'White' },
  { hex: '#EDBC9B', en: 'Light Brown', complimentary: 'Light Blue' },
  { hex: '#504267', en: 'Dark Purple', complimentary: 'Green' },
  { hex: '#939297', en: 'Gray ', complimentary: 'Dusty Pink' },
  { hex: '#E5D2CE', en: 'Light pink ', complimentary: 'Green' },
  { hex: '#FFFDD0', en: 'Cream ', complimentary: 'Orange Brown' },
  { hex: '#F5F5F5', en: 'Off White ', complimentary: 'Gray' },
  { hex: '#3A4F86', en: 'Navy Blue ', complimentary: 'Mustard Yellow' },
  { hex: '#C0C2C9', en: 'Deep Grey', complimentary: 'Cobalt Blue' },
  { hex: '#E0D2A2', en: 'Light Yellow ', complimentary: 'Purple' },
  { hex: '#F5F5DC', en: 'Beige', complimentary: 'Brown' },
  { hex: '#89CFF0', en: 'Baby Blue ', complimentary: 'Light Brown' },
  { hex: '#964B00', en: 'Dark Brown ', complimentary: 'Blue' },
]
