export const colorList = [
  { name: 'Yellow', color: '#FEFE33' },
  { name: 'Yellow-Orange', color: '#F9BB02' },
  { name: 'Orange', color: '#FB9902' },
  { name: 'Red-Orange', color: '#FD5308' },
  { name: 'Red', color: '#FE2712' },
  { name: 'Red-Violet', color: '#A6184A' },
  { name: 'Violet', color: '#8501AF' },
  { name: 'Blue-Violet', color: '#3C01A4' },
  { name: 'Blue', color: '#0246FD' },
  { name: 'Blue-Green', color: '#0392CE' },
  { name: 'Green', color: '#65AF31' },
  { name: 'Yellow-Green', color: '#D0EA2B' },
  { name: 'Biege', color: '#ece0cf' },
  { name: 'Light-Grey', color: '#d1d1d1' },
  { name: 'Dark-Grey', color: '#a1a1a1#' },
  { name: 'White', color: '#f0f0f0' },
  { name: 'Black', color: '#0f0f0f' },
]
